// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password_reset_tokens.sql

package database

import (
	"context"
	"time"
)

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (user_id, token_hash, expires_at)
VALUES (?, ?, ?)
RETURNING id, user_id, token_hash, expires_at, used, created_at, updated_at
`

type CreatePasswordResetTokenParams struct {
	UserID    int64     `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, createPasswordResetToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredPasswordResetTokens = `-- name: DeleteExpiredPasswordResetTokens :exec
DELETE FROM password_reset_tokens
WHERE expires_at < CURRENT_TIMESTAMP OR used = 1
`

func (q *Queries) DeleteExpiredPasswordResetTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredPasswordResetTokens)
	return err
}

const deleteUserPasswordResetTokens = `-- name: DeleteUserPasswordResetTokens :exec
DELETE FROM password_reset_tokens
WHERE user_id = ?
`

func (q *Queries) DeleteUserPasswordResetTokens(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserPasswordResetTokens, userID)
	return err
}

const getPasswordResetTokenByHash = `-- name: GetPasswordResetTokenByHash :one
SELECT id, user_id, token_hash, expires_at, used, created_at, updated_at FROM password_reset_tokens
WHERE token_hash = ? AND used = 0 AND expires_at > CURRENT_TIMESTAMP
`

func (q *Queries) GetPasswordResetTokenByHash(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, getPasswordResetTokenByHash, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markPasswordResetTokenUsed = `-- name: MarkPasswordResetTokenUsed :exec
UPDATE password_reset_tokens
SET used = 1, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) MarkPasswordResetTokenUsed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markPasswordResetTokenUsed, id)
	return err
}
