// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	CountUsers(ctx context.Context) (int64, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateURL(ctx context.Context, arg CreateURLParams) (Url, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error
	DeleteExpiredPasswordResetTokens(ctx context.Context) error
	DeleteExpiredRefreshTokens(ctx context.Context) error
	DeleteURL(ctx context.Context, arg DeleteURLParams) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteUserPasswordResetTokens(ctx context.Context, userID int64) error
	GetActiveRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetCategoryByID(ctx context.Context, id int64) (Category, error)
	GetPasswordResetTokenByHash(ctx context.Context, tokenHash string) (PasswordResetToken, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetURLByID(ctx context.Context, id int64) (Url, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListCategoriesByUser(ctx context.Context, userID int64) ([]Category, error)
	ListURLsByCategory(ctx context.Context, arg ListURLsByCategoryParams) ([]Url, error)
	ListURLsByUser(ctx context.Context, userID int64) ([]Url, error)
	MarkPasswordResetTokenUsed(ctx context.Context, id int64) error
	RevokeAllUserRefreshTokens(ctx context.Context, userID int64) error
	RevokeRefreshToken(ctx context.Context, tokenHash string) error
	SearchURLs(ctx context.Context, arg SearchURLsParams) ([]Url, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateURL(ctx context.Context, arg UpdateURLParams) (Url, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
