// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: urls.sql

package database

import (
	"context"
)

const createURL = `-- name: CreateURL :one
INSERT INTO urls (url, title, description, is_pinned, category_id, user_id)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, url, title, description, is_pinned, category_id, user_id, created_at, updated_at
`

type CreateURLParams struct {
	Url         string  `json:"url"`
	Title       *string `json:"title"`
	Description *string `json:"description"`
	IsPinned    bool    `json:"is_pinned"`
	CategoryID  *int64  `json:"category_id"`
	UserID      int64   `json:"user_id"`
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, createURL,
		arg.Url,
		arg.Title,
		arg.Description,
		arg.IsPinned,
		arg.CategoryID,
		arg.UserID,
	)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.IsPinned,
		&i.CategoryID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteURL = `-- name: DeleteURL :exec
DELETE FROM urls
WHERE id = ? AND user_id = ?
`

type DeleteURLParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteURL(ctx context.Context, arg DeleteURLParams) error {
	_, err := q.db.ExecContext(ctx, deleteURL, arg.ID, arg.UserID)
	return err
}

const getURLByID = `-- name: GetURLByID :one
SELECT id, url, title, description, is_pinned, category_id, user_id, created_at, updated_at FROM urls
WHERE id = ?
`

func (q *Queries) GetURLByID(ctx context.Context, id int64) (Url, error) {
	row := q.db.QueryRowContext(ctx, getURLByID, id)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.IsPinned,
		&i.CategoryID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listURLsByCategory = `-- name: ListURLsByCategory :many
SELECT id, url, title, description, is_pinned, category_id, user_id, created_at, updated_at FROM urls
WHERE category_id = ? AND user_id = ?
ORDER BY is_pinned DESC, created_at DESC
`

type ListURLsByCategoryParams struct {
	CategoryID *int64 `json:"category_id"`
	UserID     int64  `json:"user_id"`
}

func (q *Queries) ListURLsByCategory(ctx context.Context, arg ListURLsByCategoryParams) ([]Url, error) {
	rows, err := q.db.QueryContext(ctx, listURLsByCategory, arg.CategoryID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Url{}
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.IsPinned,
			&i.CategoryID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listURLsByUser = `-- name: ListURLsByUser :many
SELECT id, url, title, description, is_pinned, category_id, user_id, created_at, updated_at FROM urls
WHERE user_id = ?
ORDER BY is_pinned DESC, created_at DESC
`

func (q *Queries) ListURLsByUser(ctx context.Context, userID int64) ([]Url, error) {
	rows, err := q.db.QueryContext(ctx, listURLsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Url{}
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.IsPinned,
			&i.CategoryID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchURLs = `-- name: SearchURLs :many
SELECT id, url, title, description, is_pinned, category_id, user_id, created_at, updated_at FROM urls
WHERE user_id = ? AND (
    url LIKE ? OR
    title LIKE ? OR
    description LIKE ?
)
ORDER BY is_pinned DESC, created_at DESC
`

type SearchURLsParams struct {
	UserID      int64   `json:"user_id"`
	Url         string  `json:"url"`
	Title       *string `json:"title"`
	Description *string `json:"description"`
}

func (q *Queries) SearchURLs(ctx context.Context, arg SearchURLsParams) ([]Url, error) {
	rows, err := q.db.QueryContext(ctx, searchURLs,
		arg.UserID,
		arg.Url,
		arg.Title,
		arg.Description,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Url{}
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.IsPinned,
			&i.CategoryID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateURL = `-- name: UpdateURL :one
UPDATE urls
SET url = ?, title = ?, description = ?, is_pinned = ?, category_id = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
RETURNING id, url, title, description, is_pinned, category_id, user_id, created_at, updated_at
`

type UpdateURLParams struct {
	Url         string  `json:"url"`
	Title       *string `json:"title"`
	Description *string `json:"description"`
	IsPinned    bool    `json:"is_pinned"`
	CategoryID  *int64  `json:"category_id"`
	ID          int64   `json:"id"`
	UserID      int64   `json:"user_id"`
}

func (q *Queries) UpdateURL(ctx context.Context, arg UpdateURLParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, updateURL,
		arg.Url,
		arg.Title,
		arg.Description,
		arg.IsPinned,
		arg.CategoryID,
		arg.ID,
		arg.UserID,
	)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.IsPinned,
		&i.CategoryID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
